name: examples/cuttlefish
author: Architect.io

interfaces:
  web: ${ services.web.interfaces.main.url }

services:
  web:
    build:
      context: ./
      dockerfile: ./dockerfiles/web.Dockerfile
    description: Frontend application for cuttlefish
    language: ruby
    interfaces:
      main: 3000
    environment:
      PORT: ${ services.web.interfaces.main.port }
      REDIS_URL: redis://${ services.redis.interfaces.main.host }:${ services.redis.interfaces.main.port }
    debug:
      volumes:
        app:
          host_path: ./
          mount_path: /app
    # TODO: links: db, redis, smtp

  guard: #TODO: what is this for?
    build:
      context: ./
      dockerfile: ./dockerfiles/web.Dockerfile
    description: TODO
    language: ruby
    interfaces:
    command: bundle exec guard --no-interactions
    debug:
      volumes:
        app:
          host_path: ./
          mount_path: /app
  #   # TODO: links to db

  db:
    image: postgres:10.5
    interfaces:
      postgres: 5432

  smtp:
    build:
      context: ./
      dockerfile: ./dockerfiles/smtp.Dockerfile
    description: TODO
    language: ruby
    interfaces:
      main: 2525
    debug:
      volumes:
        app:
          host_path: ./
          mount_path: /app

  redis:
    image: redis:4.0
    interfaces:
      main: 6379

  worker:
    build:
      context: ./
      dockerfile: ./dockerfiles/worker.Dockerfile
    description: TODO
    language: ruby
    interfaces:
    environment:
      REDIS_URL: redis://${ services.redis.interfaces.main.host }:${ services.redis.interfaces.main.port }
      POSTFIX_SMTP_HOST: ${ services.postfix.interfaces.main.host }
      POSTFIX_SMTP_PORT: ${ services.postfix.interfaces.main.port }
    debug:
      volumes:
        app:
          host_path: ./
          mount_path: /app
  #   # links: TODO db redis(done) postfix(done?)

  postfix:
    image: juanluisbaptiste/postfix
    environment:
      SMTP_SERVER: ${ services.mailcatcher.interfaces.smtp.host }
      SMTP_PORT: ${ services.mailcatcher.interfaces.smtp.port }
      SMTP_USERNAME: foo@bar.com
      SMTP_PASSWORD: XXXXXXXX
      SERVER_HOSTNAME: cuttlefish.io
    interfaces:
      main: 25
    debug:
      volumes:
        postfix_logs:
          host_path: ./postfix_log
          mount_path: /var/log

  mailcatcher:
    build:
      context: ./
      dockerfile: ./dockerfiles/mailcatcher.Dockerfile
    description: TODO
    language: ruby
    interfaces:
      main: 1080
      smtp: 1025

  log:
    build:
      context: ./
      dockerfile: ./dockerfiles/log.Dockerfile
    interfaces:
    debug:
      volumes:
        app:
          host_path: ./
          mount_path: /app
        postfix_logs:
          host_path: ./postfix_log
          mount_path: /var/log
    # links db ?

# TODO: debug blocks, volumes, env vars in place of links
